package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance
import eu.kanade.domain.ui.CatppuccinColor

/**
 * Colors for Catppuccin theme
 * MIT License
 * Copyright (c) 2021 Catppuccin
 * https://catppuccin.com
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors (dark):
 * Primary #CBA6F7
 * Secondary #B4BEFE
 * Tertiary #A6E3A1
 * Neutral #181825

 * Key colors (light):
 * Primary #8839EF
 * Secondary #7287FD
 * Tertiary #40A02B
 * Neutral #E6E9EF
 */
internal object CatppuccinColorScheme : BaseColorScheme() {

    fun getColorScheme(
        isDark: Boolean,
        isAmoled: Boolean,
        primaryColor: CatppuccinColor,
    ) = super.getColorScheme(
        isDark = isDark,
        isAmoled = isAmoled,
        overrideDarkSurfaceContainers = true,
    ).let { scheme ->
        val primary = Color(if (isDark) primaryColor.mocha else primaryColor.latte)
        val onPrimary = maxContrastForeground(primary)
        scheme.copy(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primary,
            onPrimaryContainer = onPrimary,
            secondaryContainer = primary,
            onSecondaryContainer = onPrimary,
            // Unchecked switch handle and track outline
            outline = accentOrFallback(primary, scheme.surface, scheme.outline),
            // Snackbar accent
            inversePrimary = accentOrFallback(
                Color(if (isDark) primaryColor.latte else primaryColor.mocha),
                scheme.inverseSurface,
                scheme.inversePrimary,
            ), // Snackbar accent
        )
    }

    /**
     * Follows the chosen accent only where it stays readable on the surrounding surface;
     * pale accents otherwise keep the built-in Mauve role.
     */
    private fun accentOrFallback(accent: Color, background: Color, fallback: Color): Color {
        return if (contrastRatio(accent, background) >= 3f) accent else fallback
    }

    private fun maxContrastForeground(background: Color): Color {
        val dark = Color.Black
        val light = Color.White
        return if (contrastRatio(background, dark) >= contrastRatio(background, light)) dark else light
    }

    private fun contrastRatio(first: Color, second: Color): Float {
        val lighter = maxOf(first.luminance(), second.luminance())
        val darker = minOf(first.luminance(), second.luminance())
        return (lighter + 0.05f) / (darker + 0.05f)
    }

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFCBA6F7),
        onPrimary = Color(0xFF11111B),
        primaryContainer = Color(0xFFCBA6F7),
        onPrimaryContainer = Color(0xFF11111B),
        secondary = Color(0xFFB4BEFE), // Unread badge
        onSecondary = Color(0xFF11111B), // Unread badge text
        secondaryContainer = Color(0xFF313244), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFFCBA6F7), // Navigation bar selector icon
        tertiary = Color(0xFFA6E3A1), // Volume and brightness bars, Downloaded badge
        onTertiary = Color(0xFF11111B), // Downloaded badge text
        tertiaryContainer = Color(0xFF1E1E2E),
        onTertiaryContainer = Color(0xFFCDD6F4),
        error = Color(0xFFF38BA8),
        onError = Color(0xFF11111B),
        errorContainer = Color(0xFFFF0558),
        onErrorContainer = Color(0xFFEF9FB4),
        background = Color(0xFF181825),
        onBackground = Color(0xFFCDD6F4),
        surface = Color(0xFF181825),
        onSurface = Color(0xFFCDD6F4),
        surfaceVariant = Color(0xFF1E1E2E), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFCDD6F4), // Button (unselected)
        outline = Color(0xFFCBA6F7),
        outlineVariant = Color(0xFF585B70), // Outlines for buttons
        scrim = Color(0xFF11111B),
        inverseSurface = Color(0xFFEFF1F5), // Snackbar or whatever they called
        inverseOnSurface = Color(0xFF4C4F69), // Snackbar text
        inversePrimary = Color(0xFF8839EF), // Snackbar accent
        surfaceDim = Color(0xFF181825),
        surfaceBright = Color(0xFF313244),
        surfaceContainerLowest = Color(0xFF181825),
        surfaceContainerLow = Color(0xFF1E1E2E), // Repo cards
        surfaceContainer = Color(0xFF1E1E2E),
        surfaceContainerHigh = Color(0xFF1E1E2E), // Filter menu
        surfaceContainerHighest = Color(0xFF313244), // Untoggleg button bg
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF8839EF),
        onPrimary = Color(0xFFDCE0E8),
        primaryContainer = Color(0xFF8839EF),
        onPrimaryContainer = Color(0xFFDCE0E8),
        secondary = Color(0xFF7287FD), // Unread badge
        onSecondary = Color(0xFFDCE0E8), // Unread badge text
        secondaryContainer = Color(0xFFCDD0DA), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFF8839EF), // Navigation bar selector icon
        tertiary = Color(0xFF40A02B), // Volume and brightness bars, Downloaded badge
        onTertiary = Color(0xFFDCE0E8), // Downloaded badge text
        tertiaryContainer = Color(0xFFEFF1F5),
        onTertiaryContainer = Color(0xFF4C4F69),
        error = Color(0xFFD20F39),
        onError = Color(0xFFDCE0E8),
        errorContainer = Color(0xFF68001C),
        onErrorContainer = Color(0xFFD61C41),
        background = Color(0xFFE6E9EF),
        onBackground = Color(0xFF4C4F69),
        surface = Color(0xFFE6E9EF),
        onSurface = Color(0xFF4C4F69),
        surfaceVariant = Color(0xFFEFF1F5), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF4C4F69), // Button (unselected)
        outline = Color(0xFF8839EF),
        outlineVariant = Color(0xFFACB0BE), // Outlines for buttons
        scrim = Color(0xFFDCE0E8),
        inverseSurface = Color(0xFF1E1E2E), // Snackbar
        inverseOnSurface = Color(0xFFCDD6F4), // Snackbar text
        inversePrimary = Color(0xFFCBA6F7), // Snackbar accent
        surfaceDim = Color(0xFFE6E9EF),
        surfaceBright = Color(0xFFCDD0DA),
        surfaceContainerLowest = Color(0xFFE6E9EF),
        surfaceContainerLow = Color(0xFFEFF1F5), // Repo cards
        surfaceContainer = Color(0xFFEFF1F5), // Navigation bar background
        surfaceContainerHigh = Color(0xFFEFF1F5), // Filter menu
        surfaceContainerHighest = Color(0xFFCDD0DA), // Untoggleg bg
    )
}
